import React from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import TransactionList from "./TransactionList";
import type { BackendTransaction } from "../../types/receiptTypes";

const transaction = (overrides: Partial<BackendTransaction> = {}): BackendTransaction => ({
  id: "tx-receipt",
  userId: "u1",
  type: "Expense",
  paymentMethodId: null,
  toPaymentMethodId: null,
  timestamp: "2026-04-03T10:30:00Z",
  amount: 20,
  currency: "UAH",
  baseAmount: null,
  description: "Market",
  additionalNotes: null,
  balanceAfter: null,
  dataOrigin: "Receipt",
  moneyDelta: null,
  rawTransactionData: null,
  items: [{ id: "item-1", transactionId: "tx-receipt", name: "Apples", fullName: "Apples", category: null, subcategory: null, quantity: 2, pricePerUnit: 10, totalPrice: 20, origin: "ReceiptParsed" }],
  ...overrides,
});

describe("TransactionList", () => {
  it("corrects a Manual paid amount only through a separate operation and rejects reducing it below detail", async () => {
    const correct = jest.fn().mockResolvedValue(undefined);
    render(<TransactionList transactions={[transaction({ dataOrigin: "Manual", amount: 50 })]} label="Finance" onCorrectAmount={correct} />);
    fireEvent.click(screen.getByRole("button", { name: "Market" }));
    fireEvent.click(screen.getByText("Correct Manual amount"));
    fireEvent.change(screen.getByLabelText("Correct paid amount"), { target: { value: "10" } });
    expect(screen.getByRole("button", { name: "Confirm amount correction" })).toHaveProperty("disabled", true);
    fireEvent.change(screen.getByLabelText("Correct paid amount"), { target: { value: "40" } });
    fireEvent.click(screen.getByRole("button", { name: "Confirm amount correction" }));
    await waitFor(() => expect(screen.queryByLabelText("Correct paid amount")).toBeNull());
    expect(correct).toHaveBeenCalledWith(expect.objectContaining({ amount: 50 }), 40);
  });

  it("keeps original and card currencies distinct in the common header", () => {
    render(<TransactionList transactions={[transaction({ currency: "USD", amount: 5, baseAmount: 200 })]} label="Finance" paymentMethodCurrency={() => "UAH"} />);
    expect(screen.getByText(/Card amount.*200.00.*UAH/)).toBeTruthy();
  });
  it("expands inferred Bank detail with separate classification columns and preserves paid amount during editing", async () => {
    const row = transaction({ dataOrigin: "Bank", amount: 100, items: [{ ...transaction().items[0], name: "Market", fullName: "Market", quantity: 1, pricePerUnit: 0, totalPrice: 0, origin: "AutoGenerated", category: "Groceries", subcategory: "Pantry" }] });
    const save = jest.fn().mockResolvedValue(undefined);
    render(<TransactionList transactions={[row]} label="Bank" onSave={save} categories={[{ name: "Groceries", subcategories: ["Pantry", "Bakery"] }]} />);
    fireEvent.click(screen.getByRole("button", { name: /Market/ }));
    expect(screen.getByRole("columnheader", { name: "Category" })).toBeTruthy();
    expect(screen.getByRole("columnheader", { name: "Subcategory" })).toBeTruthy();
    expect(screen.getByText(/Bank-derived.*assumed/)).toBeTruthy();
    expect(screen.getByText(/Unallocated spending.*100/)).toBeTruthy();
    fireEvent.click(screen.getByTitle("More options"));
    fireEvent.click(screen.getByText("Edit"));
    expect(screen.getByLabelText("Edit item 1 price")).toHaveProperty("value", "100");
    fireEvent.change(screen.getByLabelText("Edit item 1 price"), { target: { value: "30" } });
    expect(screen.getByText(/Unallocated spending.*70/)).toBeTruthy();
    expect(screen.getByText(/100.00/)).toBeTruthy();
    fireEvent.click(screen.getByText("Save"));
    await waitFor(() => expect(screen.queryByText("Save")).toBeNull());
    expect(save).toHaveBeenCalledWith(row, expect.objectContaining({ totalAmount: 100, items: [expect.objectContaining({ unitPrice: 30 })] }));
  });

  it("retains failed local edits and Cancel makes no server mutation", async () => {
    const save = jest.fn().mockRejectedValue(new Error("Save refused"));
    render(<TransactionList transactions={[transaction({ dataOrigin: "Manual" })]} label="Finance" onSave={save} />);
    fireEvent.click(screen.getByTitle("More options"));
    fireEvent.click(screen.getByText("Edit"));
    fireEvent.change(screen.getByLabelText("Edit item 1 name"), { target: { value: "Typed detail" } });
    fireEvent.click(screen.getByText("Save"));
    await screen.findByRole("alert");
    expect(screen.getByDisplayValue("Typed detail")).toBeTruthy();
    fireEvent.click(screen.getByText("Cancel"));
    expect(save).toHaveBeenCalledTimes(1);
  });
  it("renders state details and allows keyboard users to expand receipt items", async () => {
    render(<TransactionList transactions={[transaction()]} label="Transactions" />);

    const toggle = screen.getByRole("button", { name: /market/i });
    expect(toggle.getAttribute("aria-expanded")).toBe("false");
    toggle.focus();
    await userEvent.keyboard("{Enter}");
    expect(toggle.getAttribute("aria-expanded")).toBe("true");
    expect(screen.getByText(/Apples/)).toBeTruthy();
  });

  it("selects the largest allocated Category, uses Mixed for ties, and distinguishes Income/Transfer", () => {
    const items = transaction().items;
    const rows = [transaction({ id: "groceries", description: "Dominant", items: [
      { ...items[0], category: "Groceries", totalPrice: 30 },
      { ...items[0], id: "second", category: "Dining & Takeaway", totalPrice: 10 },
    ] }), transaction({ id: "mixed", description: "Tie", items: [
      { ...items[0], category: "Groceries", totalPrice: 10 },
      { ...items[0], id: "second", category: "Dining & Takeaway", totalPrice: 10 },
    ] }), transaction({ id: "income", type: "Income" }), transaction({ id: "transfer", type: "Transfer" })];
    render(<TransactionList transactions={rows} label="Finance" />);
    expect(screen.getByRole("img", { name: "Expense · Groceries" })).toBeTruthy();
    expect(screen.getByRole("img", { name: "Expense · Mixed" })).toBeTruthy();
    expect(screen.getByRole("img", { name: "Income" })).toBeTruthy();
    expect(screen.getByRole("img", { name: "Transfer" })).toBeTruthy();
  });

  it("replaces the untouched inferred seed when adding detail, and isolates action clicks", () => {
    const row = transaction({ dataOrigin: "Bank", items: [{ ...transaction().items[0], quantity: 1, totalPrice: 0, pricePerUnit: 0, origin: "AutoGenerated" }] });
    render(<TransactionList transactions={[row]} label="Bank" onSave={jest.fn()} />);
    const toggle = screen.getByRole("button", { name: "Market" });
    fireEvent.click(screen.getByTitle("More options"));
    expect(toggle.getAttribute("aria-expanded")).toBe("false");
    fireEvent.click(screen.getByText("Edit"));
    expect(toggle.getAttribute("aria-expanded")).toBe("true");
    expect(screen.getByText("Bank-derived · assumed")).toBeTruthy();
    fireEvent.click(screen.getByText("Add Item Row"));
    expect(screen.getAllByLabelText(/Edit item.*name/)).toHaveLength(1);
    expect(screen.getByLabelText("Edit item 1 name")).toHaveProperty("value", "");
    expect(screen.getByText(/Unallocated spending.*20/)).toBeTruthy();
  });

  it("shows persistent review summaries while collapsed and keeps Income/Transfer detail read-only", () => {
    render(<TransactionList transactions={[transaction({ type: "Income", dataOrigin: "Bank", reviewCandidates: [{ id: "bill", description: "Candidate Bill", amount: 20, currency: "UAH", timestamp: null }] })]} label="Bank" onSave={jest.fn()} />);
    expect(screen.getByText("Needs review")).toBeTruthy();
    expect(screen.getByText(/Possible double counting.*Candidate Bill/)).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Market" }));
    expect(screen.queryByRole("button", { name: "More options" })).toBeNull();
  });

  it("renders every ledger origin exactly once in the all-origin list", () => {
    const rows = ["Bank", "Receipt", "Reconciled", "Manual"].map((origin, index) => transaction({
      id: `tx-${index}`,
      description: `${origin} purchase`,
      dataOrigin: origin as BackendTransaction["dataOrigin"],
      items: origin === "Reconciled" || origin === "Receipt" ? transaction().items : [],
      moneyDelta: origin === "Reconciled" ? 2 : null,
    }));
    render(<TransactionList transactions={rows} label="Finance transactions" />);

    for (const row of rows) {
      expect(screen.getAllByText(row.description)).toHaveLength(1);
    }
    expect(screen.getByText("Manual")).toBeTruthy();
    expect(screen.getByText("Provisional")).toBeTruthy();
    expect(screen.getByText("Reconciled")).toBeTruthy();
  });

  it("shows Money Delta on Reconciled rows and lets Income detail expand read-only", () => {
    render(<TransactionList transactions={[
      transaction({ id: "reconciled", dataOrigin: "Reconciled", moneyDelta: -1.25 }),
      transaction({
        id: "bank",
        dataOrigin: "Bank",
        items: [{
          ...transaction().items[0],
          id: "bank-item",
          transactionId: "bank",
          category: "Groceries",
          subcategory: "Supermarkets",
          totalPrice: 0,
          origin: "AutoGenerated",
        }],
        description: "Salary",
        type: "Income",
      }),
    ]} label="Transactions" />);

    expect(screen.getByText(/Money Delta/).textContent).toMatch(/1[.,]25/);
    expect(screen.getByRole("button", { name: /salary/i })).toBeTruthy();
    expect(screen.getByText("Salary")).toBeTruthy();
  });
});
