import React from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import TransactionList from "./TransactionList";
import type { BackendTransaction } from "../../types/receiptTypes";

const transaction = (overrides: Partial<BackendTransaction> = {}): BackendTransaction => ({
  id: "tx-receipt",
  userId: "u1",
  type: "Expense",
  paymentMethodId: null,
  toPaymentMethodId: null,
  timestamp: "2026-04-03T10:30:00Z",
  amount: 20,
  currency: "UAH",
  baseAmount: null,
  description: "Market",
  additionalNotes: null,
  balanceAfter: null,
  dataOrigin: "Receipt",
  moneyDelta: null,
  rawTransactionData: null,
  items: [{ id: "item-1", transactionId: "tx-receipt", name: "Apples", fullName: "Apples", category: null, subcategory: null, quantity: 2, pricePerUnit: 10, totalPrice: 20, origin: "ReceiptParsed" }],
  ...overrides,
});

describe("TransactionList", () => {
  it("renders state details and allows keyboard users to expand receipt items", () => {
    render(<TransactionList transactions={[transaction()]} label="Transactions" />);

    const toggle = screen.getByRole("button", { name: /market/i });
    expect(toggle.getAttribute("aria-expanded")).toBe("false");
    fireEvent.keyDown(toggle, { key: "Enter", code: "Enter" });
    fireEvent.click(toggle);
    expect(toggle.getAttribute("aria-expanded")).toBe("true");
    expect(screen.getByText(/Apples/)).toBeTruthy();
  });

  it("renders every ledger origin exactly once in the all-origin list", () => {
    const rows = ["Bank", "Receipt", "Reconciled", "Manual"].map((origin, index) => transaction({
      id: `tx-${index}`,
      description: `${origin} purchase`,
      dataOrigin: origin as BackendTransaction["dataOrigin"],
      items: origin === "Reconciled" || origin === "Receipt" ? transaction().items : [],
      moneyDelta: origin === "Reconciled" ? 2 : null,
    }));
    render(<TransactionList transactions={rows} label="Finance transactions" />);

    for (const row of rows) {
      expect(screen.getAllByText(row.description)).toHaveLength(1);
    }
    expect(screen.getByText("Manual")).toBeTruthy();
    expect(screen.getByText("Provisional")).toBeTruthy();
    expect(screen.getByText("Reconciled")).toBeTruthy();
  });

  it("shows Money Delta on Reconciled rows and keeps Bank rows compact", () => {
    render(<TransactionList transactions={[
      transaction({ id: "reconciled", dataOrigin: "Reconciled", moneyDelta: -1.25 }),
      transaction({
        id: "bank",
        dataOrigin: "Bank",
        items: [{
          ...transaction().items[0],
          id: "bank-item",
          transactionId: "bank",
          category: "Groceries",
          subcategory: "Supermarkets",
          totalPrice: 0,
          origin: "AutoGenerated",
        }],
        description: "Salary",
        type: "Income",
      }),
    ]} label="Transactions" />);

    expect(screen.getByText(/Money Delta/).textContent).toMatch(/1[.,]25/);
    expect(screen.queryByRole("button", { name: /salary/i })).toBeNull();
    expect(screen.getByText("Salary")).toBeTruthy();
  });
});
