using MyPlanner.Data.Entities.Finance;
using MyPlanner.Service.Models;

namespace MyPlanner.UnitTests.Services.Finance;

public class ExpenseBreakdownTests : FinanceServiceTests_Base
{
    private async Task<Transaction> SeedAsync(DataOrigin origin = DataOrigin.Bank)
    {
        var row = new Transaction
        {
            UserId = _testUserId, Type = TransactionType.Expense, Amount = 100m,
            Currency = Currency.USD, BaseAmount = 4000m, BalanceAfter = 5000m,
            Timestamp = new DateTime(2026, 9, 1, 12, 0, 0), Description = "Market", DataOrigin = origin,
            RawTransactionData = RawTransactionDataEnvelope.Empty.WithBank(new BankRawData(Profile: "Monobank")).ToJson()
        };
        row.Items.Add(new TransactionItem
        {
            TransactionId = row.Id, Name = "Market", FullName = "Market", Quantity = 1,
            Category = "Groceries", Subcategory = "Pantry", Origin = ItemOrigin.AutoGenerated
        });
        _testContext.Transactions.Add(row);
        await _testContext.SaveChangesAsync();
        return row;
    }

    private Transaction Payload(Transaction row, decimal amount = 999m) => new()
    {
        Id = row.Id, UserId = _testUserId, Type = TransactionType.Expense,
        Amount = amount, Currency = Currency.UAH, Description = "Retyped",
        Timestamp = DateTime.Today, DataOrigin = DataOrigin.Receipt
    };

    private TransactionItem Detail(decimal amount, string category = "Groceries", string subcategory = "Pantry") => new()
    {
        TransactionId = Guid.Empty, Name = "Bread", FullName = "Bread", Quantity = 1,
        PricePerUnit = amount, TotalPrice = amount, Category = category, Subcategory = subcategory,
        Origin = ItemOrigin.ReceiptParsed // A client cannot manufacture receipt provenance.
    };

    [Test]
    public async Task TypedBankCandidate_IsNotMergedAndBothRecordsShowReviewAfterReload()
    {
        var bank = await SeedAsync();
        await _sut.UpdateTransactionAsync(_testUserId, Payload(bank), new[] { Detail(30m) });
        var bill = new Transaction
        {
            UserId = _testUserId, Type = TransactionType.Expense, Amount = 100m,
            Currency = Currency.USD, Timestamp = bank.Timestamp, Description = "Receipt", DataOrigin = DataOrigin.Receipt
        };
        var billId = await _sut.CreateTransactionAsync(_testUserId, bill);
        await _sut.UpdateTransactionAsync(_testUserId, bill, new[] { Detail(100m) });
        _testContext.ChangeTracker.Clear();
        var ledger = await _sut.GetTransactionsAsync(_testUserId);
        Assert.Multiple(() =>
        {
            Assert.That(ledger, Has.Count.EqualTo(2));
            Assert.That(ledger.Single(t => t.Id == bank.Id).Items.Single().Name, Is.EqualTo("Bread"));
            Assert.That(ledger.Single(t => t.Id == billId).DataOrigin, Is.EqualTo(DataOrigin.Receipt));
            Assert.That(ledger.All(t => t.ReviewCandidates.Count == 1), Is.True);
        });
        await _sut.UpdateTransactionAsync(_testUserId, bill, new[] { Detail(110m) });
        ledger = await _sut.GetTransactionsAsync(_testUserId);
        Assert.That(ledger.All(t => t.ReviewCandidates.Count == 0), Is.True, "Warnings follow current candidates, not a sticky flag");
    }

    [Test]
    public async Task StaleDetailSave_IsRejectedWithoutLosingTheNewerAllocation()
    {
        var row = await SeedAsync();
        var version = row.DetailVersion;
        await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { Detail(30m) }, version);
        Assert.ThrowsAsync<InvalidOperationException>(() =>
            _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { Detail(40m) }, version));
        var saved = (await _sut.GetTransactionAsync(row.Id, _testUserId))!;
        Assert.That(saved.Items.Single().TotalPrice, Is.EqualTo(30m));
    }

    [TestCase(DataOrigin.Bank)]
    [TestCase(DataOrigin.Manual)]
    public async Task FullAllocation_AndFractionalQuantity_AreAcceptedWithoutChangingPaidAmount(DataOrigin origin)
    {
        var row = await SeedAsync(origin);
        var item = Detail(100m);
        item.Quantity = 2.5;
        item.PricePerUnit = 40m;
        var saved = (await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { item }))!;
        Assert.Multiple(() =>
        {
            Assert.That(saved.Amount, Is.EqualTo(100m));
            Assert.That(saved.DataOrigin, Is.EqualTo(origin));
            Assert.That(saved.Items.Single().TotalPrice, Is.EqualTo(100m));
        });
    }

    [TestCase("blank-name")]
    [TestCase("invalid-category")]
    [TestCase("wrong-subcategory")]
    [TestCase("invalid-quantity")]
    [TestCase("negative-price")]
    [TestCase("foreign-id")]
    [TestCase("duplicate-id")]
    [TestCase("inconsistent-cost")]
    public async Task InvalidCompleteDetail_DoesNotDeletePersistedAllocation(string scenario)
    {
        var row = await SeedAsync();
        var item = Detail(30m);
        switch (scenario)
        {
            case "blank-name": item.Name = " "; break;
            case "invalid-category": item.Category = "Invented"; break;
            case "wrong-subcategory": item.Subcategory = "Restaurants"; break;
            case "invalid-quantity": item.Quantity = double.PositiveInfinity; break;
            case "negative-price": item.PricePerUnit = -30m; break;
            case "foreign-id": item.Id = Guid.NewGuid(); break;
            case "duplicate-id": item.Id = row.Items.Single().Id; break;
            case "inconsistent-cost": item.TotalPrice = 20m; break;
        }
        Assert.ThrowsAsync<InvalidOperationException>(() => _sut.UpdateTransactionAsync(_testUserId,
            Payload(row), scenario == "duplicate-id" ? new[] { item, item } : new[] { item }));
        var saved = (await _sut.GetTransactionAsync(row.Id, _testUserId))!;
        Assert.That(saved.Items.Single().Name, Is.EqualTo("Market"));
    }

    [Test]
    public async Task ClassificationChange_BecomesUserDetailButOriginalMccSurvivesFurtherEdits()
    {
        var row = await SeedAsync();
        var item = Detail(30m, "Dining & Takeaway", "Restaurants");
        var saved = (await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { item }))!;
        var second = Detail(50m, "Transportation", "Fuel/Gas");
        saved = (await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { second }))!;
        Assert.Multiple(() =>
        {
            Assert.That(saved.Items.Single().Category, Is.EqualTo("Transportation"));
            Assert.That(saved.Items.Single().Origin, Is.EqualTo(ItemOrigin.ManualInput));
            Assert.That(EnvelopeOf(saved).Bank!.Category, Is.EqualTo("Groceries"));
            Assert.That(EnvelopeOf(saved).Bank!.Subcategory, Is.EqualTo("Pantry"));
        });
    }

    [TestCase(TransactionType.Income)]
    [TestCase(TransactionType.Transfer)]
    public async Task NonExpenseBankDetail_IsReadOnly(TransactionType type)
    {
        var row = await SeedAsync();
        row.Type = type;
        await _testContext.SaveChangesAsync();
        var payload = Payload(row);
        payload.Type = type;
        Assert.ThrowsAsync<InvalidOperationException>(() => _sut.UpdateTransactionAsync(_testUserId, payload, new[] { Detail(30m) }));
    }

    [TestCase(DataOrigin.Bank)]
    [TestCase(DataOrigin.Manual)]
    public async Task ExcessAllocation_IsRejectedAtomically(DataOrigin origin)
    {
        var row = await SeedAsync(origin);
        Assert.ThrowsAsync<InvalidOperationException>(() =>
            _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { Detail(101m) }));
        var saved = (await _sut.GetTransactionAsync(row.Id, _testUserId))!;
        Assert.That(saved.Items.Single().Origin, Is.EqualTo(ItemOrigin.AutoGenerated));
    }

    [Test]
    public async Task UnchangedInferredBankDetail_PreservesGeneratedOriginAndStoredPrices()
    {
        var row = await SeedAsync();
        var inferred = Detail(100m);
        inferred.Id = row.Items.Single().Id;
        inferred.Name = inferred.FullName = "Market";
        await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { inferred });
        var saved = (await _sut.GetTransactionAsync(row.Id, _testUserId))!;
        Assert.Multiple(() =>
        {
            Assert.That(saved.Items.Single().Origin, Is.EqualTo(ItemOrigin.AutoGenerated));
            Assert.That(saved.Items.Single().TotalPrice, Is.Zero);
        });
    }

    [Test]
    public async Task CategoryOnlyChange_IsUserDetailWithoutChangingBankKindOrOriginalMcc()
    {
        var row = await SeedAsync();
        var item = Detail(100m, "Dining & Takeaway", "Restaurants");
        item.Id = row.Items.Single().Id;
        item.Name = item.FullName = "Market";
        var saved = (await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { item }))!;
        Assert.Multiple(() =>
        {
            Assert.That(saved.DataOrigin, Is.EqualTo(DataOrigin.Bank));
            Assert.That(saved.Items.Single().Origin, Is.EqualTo(ItemOrigin.ManualInput));
            Assert.That(EnvelopeOf(saved).Bank!.Category, Is.EqualTo("Groceries"));
        });
    }

    [Test]
    public async Task ManualCorrection_CannotReducePaidAmountBelowSavedDetail()
    {
        var row = await SeedAsync(DataOrigin.Manual);
        await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { Detail(30m) });
        Assert.ThrowsAsync<InvalidOperationException>(() =>
            _sut.UpdateTransactionAsync(_testUserId, Payload(row, 20m)));
        Assert.That((await _sut.GetTransactionAsync(row.Id, _testUserId))!.Amount, Is.EqualTo(100m));
    }

    [TestCase(DataOrigin.Receipt)]
    [TestCase(DataOrigin.Reconciled)]
    public async Task StandaloneTypedBillDetail_CannotClaimParsedReceiptProvenance(DataOrigin origin)
    {
        var row = await SeedAsync(origin);
        var typed = Detail(30m);
        typed.TransactionId = row.Id;
        var id = await _sut.CreateTransactionItemAsync(_testUserId, typed);
        Assert.That((await _sut.GetTransactionItemAsync(id, _testUserId))!.Origin, Is.EqualTo(ItemOrigin.ManualInput));
        typed.Id = id;
        typed.Origin = ItemOrigin.ReceiptParsed;
        await _sut.UpdateTransactionItemAsync(_testUserId, typed);
        Assert.That((await _sut.GetTransactionItemAsync(id, _testUserId))!.Origin, Is.EqualTo(ItemOrigin.ManualInput));
    }

    [Test]
    public async Task IndependentItemWrite_CannotBypassAllocationValidation()
    {
        var row = await SeedAsync();
        var item = Detail(101m);
        item.Id = row.Items.Single().Id;
        Assert.ThrowsAsync<InvalidOperationException>(() => _sut.UpdateTransactionItemAsync(_testUserId, item));
        Assert.That((await _sut.GetTransactionAsync(row.Id, _testUserId))!.Items.Single().TotalPrice, Is.Zero);
    }

    [Test]
    public async Task PartialBankDetail_ReplacesPlaceholderWithoutChangingBankFacts()
    {
        var row = await SeedAsync();
        await _sut.UpdateTransactionAsync(_testUserId, Payload(row), new[] { Detail(30m) });
        var saved = (await _sut.GetTransactionAsync(row.Id, _testUserId))!;
        Assert.Multiple(() =>
        {
            Assert.That(saved.Amount, Is.EqualTo(100m));
            Assert.That(saved.Currency, Is.EqualTo(Currency.USD));
            Assert.That(saved.Timestamp, Is.EqualTo(new DateTime(2026, 9, 1, 12, 0, 0)));
            Assert.That(saved.DataOrigin, Is.EqualTo(DataOrigin.Bank));
            Assert.That(saved.BaseAmount, Is.EqualTo(4000m));
            Assert.That(saved.BalanceAfter, Is.EqualTo(5000m));
            Assert.That(saved.Description, Is.EqualTo("Market"));
            Assert.That(saved.Items, Has.Count.EqualTo(1));
            Assert.That(saved.Items.Single().Origin, Is.EqualTo(ItemOrigin.ManualInput));
        });
    }
}
