services:
  frontend:
    image: myPlanner/react:latest
    build: Frontends/React
    restart: always
    ports:
      - '8000:3000'
    expose:
      - '8000'
    environment:
      HTTPS: ${HTTPS}
      REACT_APP_API_URL: ${REACT_APP_API_URL}

  api:
    image: myPlanner/api:latest
    build: Backends/DotNet
    depends_on:
      - database
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      MYSQLCONNSTR_LOCALDB: ${MYSQLCONNSTR_LOCALDB}

  database:
    image: mysql
    container_name: mysql
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - '8234:80'
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  db_data:
