// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPlanner.Data.DBContexts;

#nullable disable

namespace MyPlanner.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260802133534_FinanceEntities")]
    partial class FinanceEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyPlanner.Data.Entities.Common.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ParentPage")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentPage");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Common.PageContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PageId")
                        .IsUnique();

                    b.ToTable("PageContent");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Common.PageSharing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SharedWithUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.ToTable("PageSharing");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Finance.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BankProvider")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BalanceAfter")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BaseAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RawTransactionData")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ToPaymentMethodId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ToPaymentMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Finance.TransactionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.Property<string>("Subcategory")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ListId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("TodoTasks");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoTaskSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TodoTaskId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TodoTaskId");

                    b.ToTable("TodoTasksSessions");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Notes.Note", b =>
                {
                    b.HasBaseType("MyPlanner.Data.Entities.Common.PageContent");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoList", b =>
                {
                    b.HasBaseType("MyPlanner.Data.Entities.Common.PageContent");

                    b.ToTable("TodoLists", (string)null);
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Common.Page", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Common.Page", null)
                        .WithMany("IncludePages")
                        .HasForeignKey("ParentPage")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Common.PageContent", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Common.Page", null)
                        .WithOne("Content")
                        .HasForeignKey("MyPlanner.Data.Entities.Common.PageContent", "PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Common.PageSharing", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Common.Page", null)
                        .WithMany("Sharing")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Finance.Transaction", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Finance.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyPlanner.Data.Entities.Finance.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("ToPaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Finance.TransactionItem", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Finance.Transaction", null)
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoTask", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Todo.TodoList", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoTaskSession", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Todo.TodoTask", null)
                        .WithMany("Sessions")
                        .HasForeignKey("TodoTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Notes.Note", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Common.PageContent", null)
                        .WithOne()
                        .HasForeignKey("MyPlanner.Data.Entities.Notes.Note", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoList", b =>
                {
                    b.HasOne("MyPlanner.Data.Entities.Common.PageContent", null)
                        .WithOne()
                        .HasForeignKey("MyPlanner.Data.Entities.Todo.TodoList", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Common.Page", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("IncludePages");

                    b.Navigation("Sharing");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Finance.Transaction", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoTask", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("MyPlanner.Data.Entities.Todo.TodoList", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
