import { categoryRows, summarizeReport } from "./reportSumming";
import type { BackendTransaction } from "../types/receiptTypes";

/**
 * summarizeReport — fixtures in, a category matrix and a Money Delta rollup out. The dashboard's
 * summing lives here now, so the report has one tested idea of "how much per category" and "what the
 * bank paid versus the paper". A row is always counted once: a reconciled row is summed one time,
 * never zero and never twice.
 */

/** A relative ISO timestamp, so a date fixture cannot silently age past a window the way a fixed date can. */
function when(daysAgo: number, hoursOffset = 12): string {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(hoursOffset, 0, 0, 0);
  return date.toISOString();
}

function row(overrides: Partial<BackendTransaction>): BackendTransaction {
  return {
    id: "tx-1",
    userId: "u1",
    type: "Expense",
    paymentMethodId: "pm-mono",
    toPaymentMethodId: null,
    timestamp: when(0),
    amount: 0,
    currency: "UAH",
    baseAmount: null,
    description: "SILPO",
    additionalNotes: null,
    balanceAfter: null,
    dataOrigin: "Receipt",
    moneyDelta: null,
    rawTransactionData: null,
    items: [],
    ...overrides,
  };
}

/** One line item for a fixture. */
function lineItem(name: string, category: string | null, price: number, transactionId: string): BackendTransaction["items"][number] {
  return {
    id: `${transactionId}--${name}`,
    transactionId,
    name,
    fullName: name,
    category,
    subcategory: null,
    quantity: 1,
    pricePerUnit: price,
    totalPrice: price,
    origin: "ReceiptParsed",
  };
}

/** A receipt row with one line item per (name, category, price) triple. */
function receipt(overrides: Partial<BackendTransaction>, items: [string, string, number][]) {
  return row({
    dataOrigin: "Receipt",
    items: items.map(([name, category, price]) => lineItem(name, category, price, overrides.id ?? "tx-1")),
    ...overrides,
  });
}

describe("summarizeReport — category matrix", () => {
  it("sums each line item's price into its category", () => {
    const { categoryMatrix } = summarizeReport(
      [
        receipt({ id: "a", amount: 210 }, [["Bread", "Groceries", 90], ["Milk", "Groceries", 120]]),
        receipt({ id: "b", amount: 12 }, [["Coffee", "Cafes", 12]]),
      ],
      { from: null, to: null },
    );

    expect(categoryMatrix).toEqual({ Groceries: 210, Cafes: 12 });
  });

  it("defaults an item with no category to \"Other\"", () => {
    const { categoryMatrix } = summarizeReport(
      [row({ id: "a", dataOrigin: "Receipt", items: [lineItem("misc", null, 5, "a")] })],
      { from: null, to: null },
    );

    expect(categoryMatrix).toEqual({ Other: 5 });
  });

  it("counts a Bank Transaction's full amount under MCC classification, and keeps unknown MCC spend in Other", () => {
    const classifiedBank = row({
      id: "classified-bank",
      dataOrigin: "Bank",
      amount: 40,
      items: [{ ...lineItem("Merchant", "Groceries", 0, "classified-bank"), origin: "AutoGenerated", subcategory: "Supermarkets" }],
    });
    const unclassifiedBank = row({
      id: "unclassified-bank",
      dataOrigin: "Bank",
      amount: 25,
      items: [{ ...lineItem("Merchant", null, 0, "unclassified-bank"), origin: "AutoGenerated", subcategory: null }],
    });

    const report = summarizeReport([classifiedBank, unclassifiedBank], { from: null, to: null });

    expect(report.categoryMatrix).toEqual({ Groceries: 40, Other: 25 });
    expect(report.categorySubcategoryMatrix).toEqual({ Groceries: { Supermarkets: 40 }, Other: { Other: 25 } });
    expect(report.total).toBe(65);
  });

  it("reports Category × Subcategory slices and uses AutoGenerated classification only when no real details exist", () => {
    const bank = row({
      id: "bank",
      dataOrigin: "Bank",
      amount: 40,
      items: [{ ...lineItem("Merchant", "Transport", 0, "bank"), origin: "AutoGenerated", subcategory: "Taxi" }],
    });
    const bill = receipt({ id: "bill", amount: 40 }, [["Ride", "Travel", 35]]);
    bill.items[0].subcategory = "Taxi";
    bill.items.push({ ...lineItem("generated", "Other", 40, "bill"), origin: "AutoGenerated" });

    const report = summarizeReport([bank, bill], { from: null, to: null });
    expect(report.categorySubcategoryMatrix).toEqual({ Transport: { Taxi: 40 }, Travel: { Taxi: 35 } });
    expect(report.total).toBe(75);
  });

  it("counts a categorized Manual Transaction by its TransactionItem amount", () => {
    const manual = row({
      id: "manual",
      dataOrigin: "Manual",
      amount: 42.5,
      items: [{ ...lineItem("Cash groceries", "Groceries", 42.5, "manual"), subcategory: "Pantry", origin: "ManualInput" }],
    });

    const report = summarizeReport([manual], { from: null, to: null });

    expect(report.categoryMatrix).toEqual({ Groceries: 42.5 });
    expect(report.categorySubcategoryMatrix).toEqual({ Groceries: { Pantry: 42.5 } });
    expect(report.total).toBe(42.5);
  });

  it("sums a category across several rows into one bucket", () => {
    const { categoryMatrix } = summarizeReport(
      [
        receipt({ id: "a", amount: 90 }, [["Bread", "Groceries", 90]]),
        receipt({ id: "b", amount: 60 }, [["Milk", "Groceries", 60]]),
      ],
      { from: null, to: null },
    );

    expect(categoryMatrix.Groceries).toBe(150);
  });
});

describe("summarizeReport — date range", () => {
  it("includes every row when both bounds are null", () => {
    const { categoryMatrix } = summarizeReport(
      [
        receipt({ id: "a", timestamp: when(10), amount: 10 }, [["A", "Groceries", 10]]),
        receipt({ id: "b", timestamp: when(200), amount: 20 }, [["B", "Groceries", 20]]),
      ],
      { from: null, to: null },
    );

    expect(categoryMatrix.Groceries).toBe(30);
  });

  it("drops rows before `from` and after `to`, keeping the bound days inclusive", () => {
    const { categoryMatrix } = summarizeReport(
      [
        receipt({ id: "old", timestamp: when(40), amount: 5 }, [["Old", "Groceries", 5]]),
        receipt({ id: "in", timestamp: when(5), amount: 7 }, [["In", "Groceries", 7]]),
      ],
      { from: when(10).slice(0, 10), to: new Date().toISOString().slice(0, 10) },
    );

    expect(categoryMatrix).toEqual({ Groceries: 7 });
  });

  it("counts an undated row even inside a bounded range — a row is never dropped to a missing date", () => {
    const { categoryMatrix } = summarizeReport(
      [receipt({ id: "a", timestamp: null, amount: 8 }, [["A", "Groceries", 8]])],
      { from: when(1).slice(0, 10), to: when(1).slice(0, 10) },
    );

    expect(categoryMatrix.Groceries).toBe(8);
  });
});

describe("summarizeReport — Money Delta rollup", () => {
  it("is the bank amount minus the line items for a reconciled row", () => {
    const { moneyDelta } = summarizeReport(
      [
        receipt({
          id: "a",
          dataOrigin: "Reconciled",
          amount: 390,
          timestamp: when(0),
        }, [["Bread", "Groceries", 90], ["Milk", "Groceries", 120]]),
      ],
      { from: null, to: null },
    );

    expect(moneyDelta).toEqual({ total: 180, rows: 1, byTransaction: [{ id: "a", description: "SILPO", amount: 180 }] });
  });

  it("does not count the delta of a row that is not reconciled", () => {
    const { moneyDelta, categoryMatrix } = summarizeReport(
      [
        // An unmatched bank row has a bank amount but no line items to be a delta against.
        row({ id: "b", dataOrigin: "Bank", amount: 100 }),
        // A provisional bill's amount equals its paper total, so it explains itself: no bank delta.
        receipt({ id: "a", dataOrigin: "Receipt", amount: 40 }, [["A", "Groceries", 40]]),
      ],
      { from: null, to: null },
    );

    expect(categoryMatrix).toEqual({ Groceries: 40 });
    expect(moneyDelta).toEqual({ total: 0, rows: 0, byTransaction: [] });
  });
});

describe("summarizeReport — every row counted once", () => {
  it("counts a reconciled row's line items exactly one time", () => {
    // A reconciled row is the whole purchase — the Bill and its Bank Transaction are gone. There is
    // no second row to also count, so its items appear once, and its delta is taken once.
    const { categoryMatrix, moneyDelta } = summarizeReport(
      [
        receipt({
          id: "merged",
          dataOrigin: "Reconciled",
          amount: 390,
          timestamp: when(0),
        }, [["Bread", "Groceries", 90], ["Milk", "Groceries", 120]]),
      ],
      { from: null, to: null },
    );

    expect(categoryMatrix.Groceries).toBe(210);
    expect(moneyDelta).toEqual({ total: 180, rows: 1, byTransaction: [{ id: "merged", description: "SILPO", amount: 180 }] });
  });

  it("does not double-count an unmatched pair — the bank row carries no line items to sum twice", () => {
    const { categoryMatrix } = summarizeReport(
      [
        // The provisional Bill carries the line items; its unmatched Bank twin carries none, so the
        // groceries are summed one time across the two rows, not zero and not twice.
        receipt({ id: "bill", dataOrigin: "Receipt", amount: 12.5, timestamp: when(0) }, [["Snacks", "Groceries", 12.5]]),
        row({ id: "bank", dataOrigin: "Bank", amount: 12.99, timestamp: when(0) }),
      ],
      { from: null, to: null },
    );

    expect(categoryMatrix).toEqual({ Groceries: 12.5 });
  });
});

describe("summarizeReport — owner is deferred", () => {
  it("counts the same rows whether or not an owner id is given", () => {
    const withoutOwner = summarizeReport(
      [receipt({ id: "a", amount: 10 }, [["A", "Groceries", 10]])],
      { from: null, to: null },
    );
    const withOwner = summarizeReport(
      [receipt({ id: "a", amount: 10 }, [["A", "Groceries", 10]])],
      { from: null, to: null },
      "pm-mono",
    );

    expect(withOwner).toEqual(withoutOwner);
  });
});

describe("categoryRows", () => {
  it("flattens the matrix newest-spend-first and drops zero rows", () => {
    const rows = categoryRows({ Groceries: 210, Cafes: 0, "Restaurants": 60 });

    expect(rows).toEqual([
      { category: "Groceries", amount: 210 },
      { category: "Restaurants", amount: 60 },
    ]);
  });
});
