using MyPlanner.Data.Entities.Finance;
using MyPlanner.Service.Models;

namespace MyPlanner.Service;

public partial class FinanceService
{
    private static decimal Money(decimal value) => decimal.Round(value, 2, MidpointRounding.AwayFromZero);

    // Validate the complete replacement before changing any tracked detail. Bills retain their
    // receipt accounting; Bank/Manual Expenses allocate a fixed paid amount.
    private void ReplaceLineItems(Transaction transaction, IReadOnlyList<TransactionItem> items)
    {
        var allocation = transaction.DataOrigin is DataOrigin.Bank or DataOrigin.Manual;
        if (transaction.Type != TransactionType.Expense)
            throw new InvalidOperationException("Breakdown editing is only supported for Expenses.");
        var existing = transaction.Items.ToDictionary(i => i.Id);
        if (IsUnchangedBankClassification(transaction, items)) return;

        var retainedIds = new HashSet<Guid>();
        foreach (var item in items)
        {
            ValidateBillLineItem(item);
            if (string.IsNullOrWhiteSpace(item.Name) || item.Name.Length > 200)
                throw new InvalidOperationException("Line Item Name must contain 1–200 characters.");
            if (item.Id != Guid.Empty && (!existing.ContainsKey(item.Id) || !retainedIds.Add(item.Id)))
                throw new InvalidOperationException("Line Item ID must be unique and belong to this Transaction.");
            if (item.Category != null && !ReceiptCategories.IsValidCategory(item.Category)
                || item.Subcategory != null && (item.Category == null || !ReceiptCategories.IsValidSubcategory(item.Subcategory, item.Category)))
                throw new InvalidOperationException("Select a supported Category and its Subcategory.");
            if (allocation)
            {
                try
                {
                    if (Money(item.PricePerUnit * (decimal)item.Quantity) != Money(item.TotalPrice))
                        throw new InvalidOperationException("Line Item Cost must equal Price times Quantity.");
                }
                catch (OverflowException)
                {
                    throw new InvalidOperationException("Line Item allocation is too large.");
                }
            }
        }
        if (allocation && items.Sum(i => Money(i.TotalPrice)) > Money(Math.Abs(transaction.Amount)))
            throw new InvalidOperationException("Line Item allocations cannot exceed the paid amount.");

        // Save original generated classification before replacing the active placeholder. Never
        // derive this server-owned context from a submitted Category or a legacy user allocation.
        if (transaction.DataOrigin == DataOrigin.Bank)
        {
            var envelope = RawTransactionDataEnvelope.Read(transaction.RawTransactionData);
            var source = existing.Values.FirstOrDefault(i => i.Origin == ItemOrigin.AutoGenerated);
            if (source != null && envelope.Bank?.Category == null)
                transaction.RawTransactionData = envelope.WithBank((envelope.Bank ?? new BankRawData()) with
                { Category = source.Category, Subcategory = source.Subcategory }).ToJson();
        }

        foreach (var removed in transaction.Items.Where(i => !retainedIds.Contains(i.Id)).ToArray())
        {
            _context.TransactionItems.Remove(removed);
            transaction.Items.Remove(removed);
        }
        foreach (var item in items)
        {
            if (!existing.TryGetValue(item.Id, out var stored))
            {
                stored = new TransactionItem
                {
                    TransactionId = transaction.Id, Name = item.Name, FullName = item.FullName
                };
                transaction.Items.Add(stored);
                _context.TransactionItems.Add(stored);
            }
            stored.Name = item.Name;
            stored.FullName = item.FullName;
            stored.Category = item.Category;
            stored.Subcategory = item.Subcategory;
            stored.Quantity = item.Quantity;
            stored.PricePerUnit = item.PricePerUnit;
            stored.TotalPrice = allocation ? Money(item.TotalPrice) : item.TotalPrice;
            stored.Origin = ItemOrigin.ManualInput;
        }
    }

    private static bool IsUnchangedBankClassification(Transaction transaction, IReadOnlyList<TransactionItem> items)
    {
        if (transaction.DataOrigin != DataOrigin.Bank || items.Count != 1 || transaction.Items.Count != 1)
            return false;
        var item = items[0];
        var source = transaction.Items[0];
        // Display assumptions are not a write/backfill, including on legacy source classifications.
        return source.Origin == ItemOrigin.AutoGenerated && item.Id == source.Id
            && item.Name == source.Name && item.FullName == source.FullName
            && item.Category == source.Category && item.Subcategory == source.Subcategory
            && item.Quantity == 1 && Money(item.PricePerUnit) == Money(Math.Abs(transaction.Amount))
            && Money(item.TotalPrice) == Money(Math.Abs(transaction.Amount));
    }
}
