namespace MyPlanner.Data.Entities.Finance;

public class TransactionItem : EntityBase
{
    public required Guid TransactionId { get; set; }

    public required string Name { get; set; }
    public required string FullName { get; set; }
    public string? Category { get; set; }
    public string? Subcategory { get; set; }

    public double Quantity { get; set; } = 1;
    public decimal PricePerUnit { get; set; }
    public decimal TotalPrice { get; set; }

    public ItemOrigin Origin { get; set; }
}

public enum ItemOrigin
{
    AutoGenerated, // From MCC
    ReceiptParsed,
    ManualInput,
}
