export interface Category {
  name: string;
  subcategories: string[];
}

export interface LineItem {
  // Server-side item id. Present when the line item originates from a
  // persisted transaction (backend entity) so it can be deleted server-side.
  // Absent for purely local/generated items that have no backend record.
  id?: string;
  origin?: 'AutoGenerated' | 'ReceiptParsed' | 'ManualInput';
  name: string;
  fullName: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
  category?: string;
  subcategory?: string;
}

export interface ReceiptData {
  // Backend transaction id. Present when the bill originates from a persisted
  // transaction so it can be removed at the transaction level (see
  // BillReportPanel's onDelete seam). Absent for purely generated drafts.
  id?: string;
  merchantName?: string;
  timestamp?: string | null;
  totalAmount: number;
  currency?: string;
  paymentMethod?: string;
  items: LineItem[];
  additionalNotes?: string;
}

// ── Backend entity types (directly from .NET API) ─────────────────────

export type BackendTransactionType = 'Expense' | 'Income' | 'Transfer';

export type BackendDataOrigin = 'Bank' | 'Manual' | 'Receipt' | 'Reconciled';

export interface BackendTransaction {
  id: string;
  userId: string;
  type: BackendTransactionType;
  paymentMethodId: string | null;
  toPaymentMethodId: string | null;
  timestamp: string | null; // nullable — receipts may not have a timestamp
  amount: number;
  currency: 'UAH' | 'USD' | 'EURO';
  /**
   * What the row cost in the account's own currency, straight from the statement's card-currency
   * column. Null on rows no bank statement produced — a Bill typed at the kitchen table has no
   * card figure to borrow.
   */
  baseAmount: number | null;
  description: string;
  additionalNotes: string | null;
  balanceAfter: number | null;
  dataOrigin: BackendDataOrigin;
  /** Backend-derived Money Delta; null unless the row is Reconciled. Never persisted. */
  moneyDelta: number | null;
  detailVersion?: string;
  reviewCandidates?: Array<{ id: string; description: string; amount: number; currency: BackendTransaction["currency"]; timestamp: string | null }>;
  rawTransactionData: string | null;
  createdAt?: string; // ISO date — fallback for sorting when timestamp is absent
  items: BackendTransactionItem[];
}

export interface BackendTransactionItem {
  id: string;
  transactionId: string;
  name: string;
  fullName: string;
  category: string | null;
  subcategory: string | null;
  quantity: number;
  pricePerUnit: number;
  totalPrice: number;
  origin: 'AutoGenerated' | 'ReceiptParsed' | 'ManualInput';
}

// ── DTO types for API requests ────────────────────────────────────────

export interface TransactionCreateBody {
  type: BackendTransactionType;
  paymentMethodId: null;
  toPaymentMethodId?: null;
  timestamp: string;
  amount: number;
  currency: string;
  description: string;
  additionalNotes: string | null;
  balanceAfter?: null;
  dataOrigin?: BackendDataOrigin;
}

export interface TransactionItemCreateBody {
  name: string;
  fullName: string;
  category: string | null;
  subcategory: string | null;
  quantity: number;
  pricePerUnit: number;
  totalPrice: number;
  origin?: BackendTransactionItem["origin"];
}

// ── DTO types for API updates (save-on-press commit) ───────────────

/**
 * Body for PUT /finance/transactions/{id}.
 *
 * Supplied items are the complete Expense detail ([] clears it). Omitted items retain
 * transitional header-only behaviour. Bank facts on Reconciled Bills are server-owned.
 */
export interface TransactionUpdateBody {
  id: string; // Id — required by the backend update contract
  type: BackendTransactionType;
  paymentMethodId: string | null;
  toPaymentMethodId: string | null | undefined;
  timestamp: string | null;
  amount: number;
  currency: string;
  description: string;
  additionalNotes: string | null;
  balanceAfter: number | null;
  dataOrigin: BackendDataOrigin;
  items?: Array<Omit<TransactionItemCreateBody, "origin"> & { id?: string }>;
  expectedDetailVersion?: string;
}

/** Body for PUT /finance/transactions/items/{itemId}. */
export interface TransactionItemUpdateBody {
  id: string; // Id — required by the backend update contract
  name: string;
  fullName: string;
  category?: string | null;
  subcategory?: string | null;
  quantity: number;
  pricePerUnit: number;
  totalPrice: number;
  origin?: 'AutoGenerated' | 'ReceiptParsed' | 'ManualInput';
}

// OCR preview is an unsaved Bill Draft. The response intentionally has no ledger id.
export type ProcessReceiptResponse = ReceiptData;

// ── SavedBill (frontend domain model) ─────────────────────────────────

export interface SavedBill extends ReceiptData {
  id: string;
  createdAt: string;
  tags: string[];
  dataOrigin: BackendDataOrigin;
  moneyDelta: number | null;
}
